language: php

php:
    - 7.0

before_script:
    - composer self-update
    - composer install

script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - cp phpunit.xml.dist phpunit.xml
    - php bin/console server:start
    - ./vendor/bin/simple-phpunit
    - php bin/console server:stop
