imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        dbname:   "%database_name%_test"
#        path: "%database_path%_test" #pro sqllite driver

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

parameters:
    soap_url: null #musela byse mokovat (nepodstatné testovat v úkolu)
